databases:
  - name: april-management-db
    databaseName: april_management
    user: april_user

services:
  - type: web
    name: april-management
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn manyumba.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: april-management-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
